import { Product, Order, Coupon, Staff, ContactMessage } from './types';

// Valor fixo para entrada no parcelamento por boleto
export const FIXED_BOLETO_DOWN_PAYMENT = 300.00;

// Helper for color objects - now takes an image URL
const createColor = (name: string, hex: string, image: string) => ({
  name,
  hex,
  image,
});

// Shared colors for Macs and iPads
const COLORS = {
  // MacBook Colors
  prata_mac: createColor('Prata', '#E5E4E2', 'https://i.imgur.com/Pnej5qv.jpeg'),
  cinzaEspacial_mac: createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/LbMeUgd.jpeg'),
  dourado_mac: createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/XgMEb8k.jpeg'),
  
  // iPad Colors
  prata_ipad: createColor('Prata', '#E5E4E2', 'https://i.imgur.com/oJMbE1Z.jpeg'),
  preto_ipad_pro: createColor('Preto', '#2C2C2E', 'https://i.imgur.com/s8NJWCb.jpeg'),
  rosa_ipad: createColor('Rosa', '#F5D7E3', 'https://i.imgur.com/BLxMrEk.jpeg'),
  amarelo_ipad: createColor('Amarelo', '#FDE48B', 'https://i.imgur.com/4u8DDai.jpeg'),
  azul_ipad: createColor('Azul', '#A7C9DE', 'https://i.imgur.com/LDEIUCN.jpeg'),
  verde_ipad: createColor('Verde', '#A7C9A7', 'https://i.imgur.com/TuwAAe0.jpeg'),
};


export const MOCK_PRODUCTS: Product[] = [
  // --- iPads (Novo) ---
  {
    id: 'ipad-10-wifi-64gb-novo',
    name: 'iPad 10 Wi-Fi 64GB',
    description: 'Tela Liquid Retina de 10,9 polegadas, chip A14 Bionic e design colorido.',
    longDescription: 'O novo iPad foi redesenhado para ser mais versátil. Com uma tela Liquid Retina de ponta a ponta, quatro cores incríveis e acessórios essenciais, ele é perfeito para tudo.',
    technicalSpecs: { Tela: 'Liquid Retina de 10,9"', Capacidade: '64GB', Chip: 'A14 Bionic', Conectividade: 'Wi-Fi' },
    price: 2499.00, stock: 25, condition: 'Novo', storage: '64GB',
    availableColors: [COLORS.prata_ipad, COLORS.azul_ipad, COLORS.amarelo_ipad, COLORS.rosa_ipad],
    defaultImage: 'https://i.imgur.com/TBnO1sf.jpeg', warranty: '12 meses Apple', category: 'iPad',
    tags: ['ipad', 'a14', 'novo'], salesCount: 85, isOfficial: true, freeShipping: false,
  },
  {
    id: 'ipad-10-wifi-256gb-novo',
    name: 'iPad 10 Wi-Fi 256GB',
    description: 'Tela Liquid Retina de 10,9 polegadas, chip A14 Bionic e design colorido.',
    longDescription: 'O novo iPad foi redesenhado para ser mais versátil. Com uma tela Liquid Retina de ponta a ponta, quatro cores incríveis e acessórios essenciais, ele é perfeito para tudo.',
    technicalSpecs: { Tela: 'Liquid Retina de 10,9"', Capacidade: '256GB', Chip: 'A14 Bionic', Conectividade: 'Wi-Fi' },
    price: 2999.00, stock: 18, condition: 'Novo', storage: '256GB',
    availableColors: [COLORS.prata_ipad, COLORS.azul_ipad, COLORS.amarelo_ipad, COLORS.rosa_ipad],
    defaultImage: 'https://i.imgur.com/TBnO1sf.jpeg', warranty: '12 meses Apple', category: 'iPad',
    tags: ['ipad', 'a14', 'novo'], salesCount: 50, isOfficial: true, freeShipping: true,
  },
  {
    id: 'ipad-air-m2-11-256gb-novo',
    name: 'iPad Air M2 11” Wi-Fi 256GB',
    description: 'Potência incrível com o chip M2. Tela Liquid Retina de 11 polegadas e design fino e leve.',
    longDescription: 'O iPad Air agora vem com o chip M2, que traz um desempenho surpreendente. Com a tela Liquid Retina e o design fino e leve, você pode trabalhar e criar em qualquer lugar.',
    technicalSpecs: { Tela: 'Liquid Retina de 11"', Capacidade: '256GB', Chip: 'M2', Conectividade: 'Wi-Fi' },
    price: 5299.00, stock: 12, condition: 'Novo', storage: '256GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/DydaIOS.jpeg'), createColor('Dourado', '#F5D7E3', 'https://i.imgur.com/9p4R2Cp.jpeg'), COLORS.verde_ipad, createColor('Azul', '#A7C9DE', 'https://i.imgur.com/naiEwGG.jpeg')],
    defaultImage: 'https://i.imgur.com/aj8krhp.jpeg', warranty: '12 meses Apple', category: 'iPad',
    tags: ['ipad', 'air', 'm2', 'novo'], salesCount: 65, isOfficial: true, freeShipping: true,
  },
   {
    id: 'ipad-air-m2-13-128gb-novo',
    name: 'iPad Air M2 13” Wi-Fi 128GB',
    description: 'A experiência do Air em uma tela maior. Chip M2, design fino e leve.',
    longDescription: 'O iPad Air de 13 polegadas com chip M2 oferece um desempenho incrível em uma tela Liquid Retina espaçosa. Ideal para multitarefa, criação e entretenimento.',
    technicalSpecs: { Tela: 'Liquid Retina de 13"', Capacidade: '128GB', Chip: 'M2', Conectividade: 'Wi-Fi' },
    price: 5499.00, stock: 15, condition: 'Novo', storage: '128GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/Cf5utUK.jpeg'), createColor('Dourado', '#F5D7E3', 'https://i.imgur.com/ZfNVUKD.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/BxbHpMX.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/p2PyC3T.jpeg')],
    defaultImage: 'https://i.imgur.com/6hyxs6u.jpeg', warranty: '12 meses Apple', category: 'iPad',
    tags: ['ipad', 'air', 'm2', '13-inch', 'novo'], salesCount: 45, isOfficial: true, freeShipping: true,
  },
   {
    id: 'ipad-air-m3-11-128gb-novo',
    name: 'iPad Air M3 11” Wi-Fi 128GB',
    description: 'O novo iPad Air com a potência do chip M3. Mais rápido e mais inteligente.',
    longDescription: 'Leve seu trabalho e criatividade a outro nível com o iPad Air M3. Desempenho gráfico e de IA aprimorados em um design portátil que você já ama.',
    technicalSpecs: { Tela: 'Liquid Retina de 11"', Capacidade: '128GB', Chip: 'M3', Conectividade: 'Wi-Fi' },
    price: 4099.00, stock: 20, condition: 'Novo', storage: '128GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/BBqL4YM.jpeg'), createColor('Dourado', '#F5D7E3', 'https://i.imgur.com/HenAd4U.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/hnaVsd7.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/aVkUPum.jpeg')],
    defaultImage: 'https://i.imgur.com/BBqL4YM.jpeg', warranty: '12 meses Apple', category: 'iPad',
    tags: ['ipad', 'air', 'm3', 'novo'], salesCount: 30, isOfficial: true, freeShipping: true,
  },
  {
    id: 'ipad-pro-m4-11-256gb-novo',
    name: 'iPad Pro M4 11” Wi-Fi 256GB',
    description: 'A experiência definitiva em iPad. O desempenho absurdo do chip M4 e a tela Ultra Retina XDR.',
    longDescription: 'O novo iPad Pro é incrivelmente fino e leve, e vem com o desempenho revolucionário do chip M4. A tela Ultra Retina XDR é a mais avançada do mundo.',
    technicalSpecs: { Tela: 'Ultra Retina XDR de 11"', Capacidade: '256GB', Chip: 'M4', Conectividade: 'Wi-Fi' },
    price: 6799.00, stock: 8, condition: 'Novo', storage: '256GB',
    availableColors: [COLORS.preto_ipad_pro, createColor('Prata', '#F5F5F7', 'https://i.imgur.com/vZ5OBek.jpeg')],
    defaultImage: 'https://i.imgur.com/p4LdZMy.jpeg', warranty: '12 meses Apple', category: 'iPad',
    tags: ['ipad', 'pro', 'm4', 'novo'], salesCount: 40, isOfficial: true, freeShipping: true,
  },

  // --- MacBooks (Novo) ---
  {
    id: 'macbook-air-m1-13-2020-256gb-novo',
    name: 'MacBook Air M1 13” 2020 256GB',
    description: 'O chip M1 da Apple redefine o notebook mais fino e leve. CPU até 3,5x mais rápida. GPU até 5x mais veloz.',
    longDescription: 'O MacBook Air com chip M1 é um monstro de desempenho. A CPU de 8 núcleos encara projetos pesados e a GPU de 7 núcleos acelera os games e apps mais exigentes.',
    technicalSpecs: { Tela: 'Retina de 13,3"', Capacidade: '256GB SSD', Chip: 'M1', Memória: '8GB' },
    price: 4899.00, stock: 20, condition: 'Novo', storage: '256GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/NIE0g36.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/IxLz5kk.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/rJx0fE4.jpeg')],
    defaultImage: 'https://i.imgur.com/2E0G4Qk.jpeg', warranty: '12 meses Apple', category: 'MacBook',
    tags: ['macbook', 'air', 'm1', 'novo'], salesCount: 300, isOfficial: true, freeShipping: true,
  },
  {
    id: 'macbook-air-m2-13-2022-256gb-novo',
    name: 'MacBook Air M2 13” 2022 256GB',
    description: 'Novo design, chip M2 de última geração e até 18 horas de bateria. Fino, rápido e poderoso.',
    longDescription: 'Totalmente redesenhado em torno do chip M2, o MacBook Air combina potência e eficiência em uma estrutura de alumínio reciclado resistente.',
    technicalSpecs: { Tela: 'Liquid Retina de 13,6"', Capacidade: '256GB SSD', Chip: 'M2', Memória: '8GB' },
    price: 6699.00, stock: 18, condition: 'Novo', storage: '256GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/a1QhSxq.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/rZMNKje.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/urjJn3a.jpeg')],
    defaultImage: 'https://i.imgur.com/WDlorE5.jpeg', warranty: '12 meses Apple', category: 'MacBook',
    tags: ['macbook', 'air', 'm2', 'novo'], salesCount: 250, isOfficial: true, freeShipping: true,
  },
  {
    id: 'macbook-air-m3-13-2024-256gb-novo',
    name: 'MacBook Air M3 13” 2024 256GB',
    description: 'O MacBook Air com M3 aproveita o desempenho e os recursos de IA do novo chip para ficar ainda melhor.',
    longDescription: 'Leve, fino e agora com o poder do M3. O MacBook Air é o notebook perfeito para trabalhar, jogar e criar em qualquer lugar, com uma eficiência energética incrível.',
    technicalSpecs: { Tela: 'Liquid Retina de 13,6"', Capacidade: '256GB SSD', Chip: 'M3', Memória: '8GB' },
    price: 8799.00, stock: 15, condition: 'Novo', storage: '256GB',
    availableColors: [COLORS.prata_mac, COLORS.cinzaEspacial_mac, COLORS.dourado_mac],
    defaultImage: 'https://i.imgur.com/paCKdzl.jpeg', warranty: '12 meses Apple', category: 'MacBook',
    tags: ['macbook', 'air', 'm3', 'novo'], salesCount: 180, isOfficial: true, freeShipping: true,
  },
   {
    id: 'macbook-air-m3-15-2024-512gb-novo',
    name: 'MacBook Air M3 15” 2024 512GB',
    description: 'Tela Liquid Retina de 15 polegadas e o poder do chip M3. Mais espaço para suas ideias.',
    longDescription: 'O MacBook Air de 15 polegadas com chip M3 é a combinação perfeita de portabilidade e potência em uma tela maior, ideal para profissionais e estudantes.',
    technicalSpecs: { Tela: 'Liquid Retina de 15,3"', Capacidade: '512GB SSD', Chip: 'M3', Memória: '8GB' },
    price: 10499.00, stock: 10, condition: 'Novo', storage: '512GB',
    availableColors: [COLORS.prata_mac, COLORS.cinzaEspacial_mac, COLORS.dourado_mac],
    defaultImage: 'https://i.imgur.com/paCKdzl.jpeg', warranty: '12 meses Apple', category: 'MacBook',
    tags: ['macbook', 'air', 'm3', '15-inch', 'novo'], salesCount: 110, isOfficial: true, freeShipping: true,
  },
  {
    id: 'macbook-air-m4-13-2025-256gb-novo',
    name: 'MacBook Air M4 13” 2025 256GB',
    description: 'Performance de outro mundo com o chip M4. A revolução da inteligência artificial no seu notebook.',
    longDescription: 'O MacBook Air M4 não é apenas rápido, é inteligente. Com o Neural Engine mais avançado, ele acelera tarefas de IA e transforma sua produtividade.',
    technicalSpecs: { Tela: 'Liquid Retina de 13,6"', Capacidade: '256GB SSD', Chip: 'M4', Memória: '16GB' },
    price: 9999.00, stock: 10, condition: 'Novo', storage: '256GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/sChRiFb.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/8leSUTS.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/jy08XGm.jpeg')],
    defaultImage: 'https://i.imgur.com/rUCSlWJ.jpeg', warranty: '12 meses Apple', category: 'MacBook',
    tags: ['macbook', 'air', 'm4', 'novo'], salesCount: 90, isOfficial: true, freeShipping: true,
  },
    {
    id: 'macbook-air-m4-15-2025-256gb-novo',
    name: 'MacBook Air M4 15” 2025 256GB',
    description: 'A incrível performance do chip M4 em uma tela Liquid Retina de 15 polegadas.',
    longDescription: 'O MacBook Air M4 de 15 polegadas oferece um equilíbrio perfeito entre tamanho de tela, performance e portabilidade. Ideal para quem precisa de mais espaço sem abrir mão da leveza.',
    technicalSpecs: { Tela: 'Liquid Retina de 15,3"', Capacidade: '256GB SSD', Chip: 'M4', Memória: '16GB' },
    price: 10699.00, stock: 8, condition: 'Novo', storage: '256GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/sChRiFb.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/8leSUTS.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/jy08XGm.jpeg')],
    defaultImage: 'https://i.imgur.com/rUCSlWJ.jpeg', warranty: '12 meses Apple', category: 'MacBook',
    tags: ['macbook', 'air', 'm4', '15-inch', 'novo'], salesCount: 60, isOfficial: true, freeShipping: true,
  },
  {
    id: 'macbook-pro-m4-14-2024-512gb-novo',
    name: 'MacBook Pro M4 14” 2024 512GB',
    description: 'O notebook profissional levado ao extremo. O chip M4 traz um desempenho que devora qualquer tarefa.',
    longDescription: 'Para os profissionais que não abrem mão de nada. O MacBook Pro M4 oferece desempenho gráfico e de CPU de nível profissional, a melhor tela e a maior autonomia em um Mac.',
    technicalSpecs: { Tela: 'Liquid Retina XDR de 14"', Capacidade: '512GB SSD', Chip: 'M4', Memória: '16GB' },
    price: 12499.00, stock: 8, condition: 'Novo', storage: '512GB',
    availableColors: [COLORS.prata_mac, COLORS.cinzaEspacial_mac],
    defaultImage: COLORS.prata_mac.image, warranty: '12 meses Apple', category: 'MacBook',
    tags: ['macbook', 'pro', 'm4', 'novo'], salesCount: 55, isOfficial: true, freeShipping: true,
  },
  
  // --- iPhones (Novo / Lacrado) ---
  {
    id: 'iphone-13-128gb-novo',
    name: 'iPhone 13 128GB',
    description: 'Sistema de câmera dupla avançado, chip A15 Bionic e um grande salto na duração da bateria.',
    longDescription: 'O iPhone 13 possui uma tela Super Retina XDR brilhante. O chip A15 Bionic ultrarrápido potencializa o Modo Cinema, Estilos Fotográficos e muito mais.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,1"', Capacidade: '128GB', Chip: 'A15 Bionic', Câmera: 'Dupla de 12MP' },
    price: 3399.00, stock: 45, condition: 'Novo', storage: '128GB',
    availableColors: [createColor('Verde', '#A7C9A7', 'https://i.imgur.com/xoAFZro.jpeg'), createColor('Rosa', '#F5D7E3', 'https://i.imgur.com/f0Fezf0.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/UrkB8CP.jpeg'), createColor('Preto', '#2C2C2E', 'https://i.imgur.com/LF5L338.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/c9mTG2U.jpeg')],
    defaultImage: 'https://i.imgur.com/Mf4xFmu.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone13', 'a15', 'novo'], salesCount: 450, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-14-128gb-novo',
    name: 'iPhone 14 128GB',
    description: 'Com detecção de acidente, a maior autonomia de sempre e fotos ainda mais espetaculares com pouca luz.',
    longDescription: 'O iPhone 14 vem com Deteção de acidente, uma funcionalidade de segurança vital que liga para o 112 por si. A maior autonomia de sempre e fotos ainda mais espetaculares com pouca luz.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,1"', Capacidade: '128GB', Chip: 'A15 Bionic', Câmera: 'Dupla de 12MP' },
    price: 3699.00, stock: 50, condition: 'Novo', storage: '128GB',
    availableColors: [createColor('Azul', '#A7C9DE', 'https://i.imgur.com/GWot19i.jpeg'), createColor('Lilás', '#E2D8EB', 'https://i.imgur.com/mwFbMjt.jpeg'), createColor('Preto', '#2C2C2E', 'https://i.imgur.com/HX4NKsw.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/1HYrRPs.jpeg'), createColor('Vermelho', '#FF3B30', 'https://i.imgur.com/VlxTVNV.jpeg')],
    defaultImage: 'https://i.imgur.com/PyEBZBy.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone14', 'a15', 'novo'], salesCount: 800, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-15-128gb-novo',
    name: 'iPhone 15 128GB',
    description: 'Dynamic Island, câmera grande-angular de 48MP e USB-C. Tudo em um design resistente.',
    longDescription: 'A Dynamic Island mostra alertas e Atividades ao Vivo para você não perder nada. Veja quem está ligando, o status do seu voo e muito mais.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,1"', Capacidade: '128GB', Chip: 'A16 Bionic', Câmera: 'Grande-angular 48MP' },
    price: 4099.00, stock: 60, condition: 'Novo', storage: '128GB',
    availableColors: [createColor('Azul', '#A7C9DE', 'https://i.imgur.com/usUQcjg.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/qzsHZQ8.jpeg'), createColor('Preto', '#2C2C2E', 'https://i.imgur.com/CnTVA6R.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/t2gqFl7.jpeg'), createColor('Amarelo', '#FDE48B', 'https://i.imgur.com/5ZSALGQ.jpeg')],
    defaultImage: 'https://i.imgur.com/5asp3Kj.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone15', 'a16', 'dynamic-island', 'novo'], salesCount: 1100, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-15-256gb-novo',
    name: 'iPhone 15 256GB',
    description: 'Dynamic Island, câmera grande-angular de 48MP e USB-C. Tudo em um design resistente.',
    longDescription: 'A Dynamic Island mostra alertas e Atividades ao Vivo para você não perder nada. Veja quem está ligando, o status do seu voo e muito mais.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,1"', Capacidade: '256GB', Chip: 'A16 Bionic', Câmera: 'Grande-angular 48MP' },
    price: 5099.00, stock: 40, condition: 'Novo', storage: '256GB',
    availableColors: [createColor('Azul', '#A7C9DE', 'https://i.imgur.com/usUQcjg.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/qzsHZQ8.jpeg'), createColor('Preto', '#2C2C2E', 'https://i.imgur.com/CnTVA6R.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/t2gqFl7.jpeg'), createColor('Amarelo', '#FDE48B', 'https://i.imgur.com/5ZSALGQ.jpeg')],
    defaultImage: 'https://i.imgur.com/5asp3Kj.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone15', 'a16', 'dynamic-island', 'novo'], salesCount: 550, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-16-128gb-novo',
    name: 'iPhone 16 128GB',
    description: 'O futuro chegou. Desempenho inigualável com o novo chip A18 e um sistema de câmera revolucionário.',
    longDescription: 'O iPhone 16 redefine a velocidade e a inteligência em um smartphone. Com o chip A18, suas tarefas e jogos voam. A nova câmera captura detalhes nunca antes vistos.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,1"', Capacidade: '128GB', Chip: 'A18 Bionic', Câmera: 'Dupla de 48MP' },
    price: 4999.00, stock: 50, condition: 'Novo', storage: '128GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/aHHGYLS.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/nABwUmC.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/tMBOMFZ.jpeg'), createColor('Rosa', '#F5D7E3', 'https://i.imgur.com/5oWftRD.jpeg')],
    defaultImage: 'https://i.imgur.com/5Y6MV3n.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone16', 'a18', 'novo'], salesCount: 95, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-16e-128gb-novo',
    name: 'iPhone 16E 128GB',
    description: 'Potência e elegância em um design acessível. O essencial do iPhone 16 para o seu dia a dia.',
    longDescription: 'O iPhone 16E oferece o poderoso chip A17 em um design clássico e amado. Ideal para quem busca performance e um ótimo custo-benefício.',
    technicalSpecs: { Tela: 'Retina XDR de 6,1"', Capacidade: '128GB', Chip: 'A17 Bionic', Câmera: '12MP' },
    price: 3899.00, stock: 40, condition: 'Novo', storage: '128GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/4Uyrsx2.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/4PADhco.jpeg')],
    defaultImage: 'https://i.imgur.com/MGBCPza.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone16e', 'a17', 'novo'], salesCount: 120, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-16-plus-128gb-novo',
    name: 'iPhone 16 Plus 128GB',
    description: 'Tela gigante, bateria gigante. Sua experiência em um iPhone, agora em tamanho Plus.',
    longDescription: 'O iPhone 16 Plus traz uma tela Super Retina XDR de 6,7 polegadas e a melhor bateria em um iPhone. Perfeito para maratonar séries e jogar.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,7"', Capacidade: '128GB', Chip: 'A18 Bionic', Câmera: 'Dupla de 48MP' },
    price: 5799.00, stock: 35, condition: 'Novo', storage: '128GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/ob7tlGQ.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/v34zHNu.jpeg'), createColor('Rosa', '#F5D7E3', 'https://i.imgur.com/YL1QV2v.jpeg')],
    defaultImage: 'https://i.imgur.com/ob7tlGQ.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone16', 'plus', 'a18', 'novo'], salesCount: 70, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-16-pro-128gb-novo',
    name: 'iPhone 16 Pro 128GB',
    description: 'O iPhone para quem exige o máximo. Chip A18 Pro e o sistema de câmera Pro mais avançado.',
    longDescription: 'O iPhone 16 Pro é forjado em titânio e conta com o revolucionário chip A18 Pro, um botão de Ação configurável e o sistema de câmera Pro mais versátil.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1" ProMotion', Capacidade: '128GB', Chip: 'A18 Pro', Câmera: 'Tripla Pro de 48MP' },
    price: 6099.00, stock: 40, condition: 'Novo', storage: '128GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/GKqPG6Y.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/QlQ3te3.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/1TscPJ9.png')],
    defaultImage: 'https://i.imgur.com/3n0XnlJ.png', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone16', 'pro', 'a18pro', 'novo'], salesCount: 150, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-16-pro-256gb-novo',
    name: 'iPhone 16 Pro 256GB',
    description: 'O iPhone para quem exige o máximo. Chip A18 Pro e o sistema de câmera Pro mais avançado.',
    longDescription: 'O iPhone 16 Pro é forjado em titânio e conta com o revolucionário chip A18 Pro, um botão de Ação configurável e o sistema de câmera Pro mais versátil.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1" ProMotion', Capacidade: '256GB', Chip: 'A18 Pro', Câmera: 'Tripla Pro de 48MP' },
    price: 7199.00, stock: 25, condition: 'Novo', storage: '256GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/GKqPG6Y.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/QlQ3te3.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/1TscPJ9.png')],
    defaultImage: 'https://i.imgur.com/3n0XnlJ.png', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone16', 'pro', 'a18pro', 'novo'], salesCount: 110, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-16-pro-max-256gb-novo',
    name: 'iPhone 16 Pro Max 256GB',
    description: 'A experiência Pro definitiva. Tela gigante, chip A18 Pro e o maior zoom óptico em um iPhone.',
    longDescription: 'Com a maior tela e a maior autonomia de um iPhone, o iPhone 16 Pro Max é a ferramenta definitiva para criadores e profissionais.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7" ProMotion', Capacidade: '256GB', Chip: 'A18 Pro', Câmera: 'Tripla Pro 48MP com Zoom 5x' },
    price: 7299.00, stock: 30, condition: 'Novo', storage: '256GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/Im13V9m.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/NAkYJQL.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/F4NkIeP.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/uHk1umw.jpeg')],
    defaultImage: 'https://i.imgur.com/bXV1ART.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone16', 'pro', 'max', 'a18pro', 'novo'], salesCount: 200, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-16-pro-max-512gb-novo',
    name: 'iPhone 16 Pro Max 512GB',
    description: 'A experiência Pro definitiva. Tela gigante, chip A18 Pro e o maior zoom óptico em um iPhone.',
    longDescription: 'Com a maior tela e a maior autonomia de um iPhone, o iPhone 16 Pro Max é a ferramenta definitiva para criadores e profissionais.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7" ProMotion', Capacidade: '512GB', Chip: 'A18 Pro', Câmera: 'Tripla Pro 48MP com Zoom 5x' },
    price: 8699.00, stock: 20, condition: 'Novo', storage: '512GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/Im13V9m.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/NAkYJQL.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/F4NkIeP.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/uHk1umw.jpeg')],
    defaultImage: 'https://i.imgur.com/bXV1ART.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone16', 'pro', 'max', 'a18pro', 'novo'], salesCount: 140, isOfficial: true, freeShipping: true,
  },
  {
    id: 'iphone-16-pro-max-1tb-novo',
    name: 'iPhone 16 Pro Max 1TB',
    description: 'A experiência Pro definitiva com armazenamento massivo para todos os seus arquivos.',
    longDescription: 'Com 1TB de espaço, o iPhone 16 Pro Max é a ferramenta definitiva para criadores e profissionais que precisam de muito armazenamento.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7" ProMotion', Capacidade: '1TB', Chip: 'A18 Pro', Câmera: 'Tripla Pro 48MP com Zoom 5x' },
    price: 10899.00, stock: 10, condition: 'Novo', storage: '1TB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/Im13V9m.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/NAkYJQL.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/F4NkIeP.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/uHk1umw.jpeg')],
    defaultImage: 'https://i.imgur.com/bXV1ART.jpeg', warranty: '12 meses Apple', category: 'iPhone',
    tags: ['iphone16', 'pro', 'max', 'a18pro', '1tb', 'novo'], salesCount: 80, isOfficial: true, freeShipping: true,
  },

  // --- iPhones (Seminovo) ---
  {
    id: 'iphone-11-64gb-seminovo', name: 'iPhone 11 64GB',
    description: 'O iPhone 11 com chip A13 Bionic, sistema de câmera dupla e design resistente.',
    longDescription: 'Capture fotos e vídeos incríveis com as câmeras ultra-angular e grande-angular. Veja cores realistas em fotos, vídeos e jogos na tela Liquid Retina de 6,1 polegadas. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Liquid Retina HD 6,1"', Capacidade: '64GB', Chip: 'A13 Bionic', Câmera: 'Dupla de 12MP' },
    price: 1499.00, stock: 35, condition: 'Seminovo', storage: '64GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/tDHFdQT.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/yip4raN.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/4yLECT1.jpeg'), createColor('Roxo', '#C7BEDD', 'https://i.imgur.com/SsxgwVS.jpeg')], 
    defaultImage: 'https://i.imgur.com/5UmCMUU.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '11', 'seminovo', 'a13'],
    salesCount: 350, isOfficial: false, freeShipping: false,
  },
  {
    id: 'iphone-11-128gb-seminovo', name: 'iPhone 11 128GB',
    description: 'O iPhone 11 com chip A13 Bionic, sistema de câmera dupla e design resistente.',
    longDescription: 'Capture fotos e vídeos incríveis com as câmeras ultra-angular e grande-angular. Veja cores realistas em fotos, vídeos e jogos na tela Liquid Retina de 6,1 polegadas. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Liquid Retina HD 6,1"', Capacidade: '128GB', Chip: 'A13 Bionic', Câmera: 'Dupla de 12MP' },
    price: 1699.00, stock: 28, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/tDHFdQT.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/yip4raN.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/4yLECT1.jpeg'), createColor('Roxo', '#C7BEDD', 'https://i.imgur.com/SsxgwVS.jpeg')], 
    defaultImage: 'https://i.imgur.com/5UmCMUU.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '11', 'seminovo', 'a13'],
    salesCount: 420, isOfficial: false, freeShipping: false,
  },
   {
    id: 'iphone-11-pro-64gb-seminovo', name: 'iPhone 11 Pro 64GB',
    description: 'Sistema de câmera tripla Pro, tela Super Retina XDR e o potente chip A13 Bionic.',
    longDescription: 'O iPhone 11 Pro eleva a fotografia a outro nível com seu sistema de câmera tripla. A tela Super Retina XDR oferece uma experiência visual imersiva. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 5,8"', Capacidade: '64GB', Chip: 'A13 Bionic', Câmera: 'Tripla de 12MP' },
    price: 1799.00, stock: 22, condition: 'Seminovo', storage: '64GB',
    availableColors: [createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/ssQuBPp.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/CXLU8i3.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/MGiBL1P.jpeg')], 
    defaultImage: 'https://i.imgur.com/RjDSZom.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '11', 'pro', 'seminovo', 'a13'],
    salesCount: 280, isOfficial: false, freeShipping: false,
  },
   {
    id: 'iphone-11-pro-256gb-seminovo', name: 'iPhone 11 Pro 256GB',
    description: 'Sistema de câmera tripla Pro, tela Super Retina XDR e o potente chip A13 Bionic.',
    longDescription: 'O iPhone 11 Pro eleva a fotografia a outro nível com seu sistema de câmera tripla. A tela Super Retina XDR oferece uma experiência visual imersiva. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 5,8"', Capacidade: '256GB', Chip: 'A13 Bionic', Câmera: 'Tripla de 12MP' },
    price: 1999.00, stock: 15, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/ssQuBPp.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/CXLU8i3.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/MGiBL1P.jpeg')], 
    defaultImage: 'https://i.imgur.com/RjDSZom.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '11', 'pro', 'seminovo', 'a13'],
    salesCount: 310, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-11-pro-max-64gb-seminovo', name: 'iPhone 11 Pro Max 64GB',
    description: 'A maior tela e a melhor bateria da linha 11 Pro, com sistema de câmera tripla.',
    longDescription: 'Desfrute de uma experiência cinematográfica na tela Super Retina XDR de 6,5 polegadas. O iPhone 11 Pro Max oferece performance e câmeras profissionais. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,5"', Capacidade: '64GB', Chip: 'A13 Bionic', Câmera: 'Tripla de 12MP' },
    price: 1999.00, stock: 18, condition: 'Seminovo', storage: '64GB',
    availableColors: [createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/9u8V2w8.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/IZzsvcS.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/JUXK210.jpeg')], 
    defaultImage: 'https://i.imgur.com/3KrpgWS.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '11', 'pro', 'max', 'seminovo', 'a13'],
    salesCount: 250, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-11-pro-max-256gb-seminovo', name: 'iPhone 11 Pro Max 256GB',
    description: 'A maior tela e a melhor bateria da linha 11 Pro, com sistema de câmera tripla.',
    longDescription: 'Desfrute de uma experiência cinematográfica na tela Super Retina XDR de 6,5 polegadas. O iPhone 11 Pro Max oferece performance e câmeras profissionais. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,5"', Capacidade: '256GB', Chip: 'A13 Bionic', Câmera: 'Tripla de 12MP' },
    price: 2299.00, stock: 12, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/9u8V2w8.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/IZzsvcS.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/JUXK210.jpeg')], 
    defaultImage: 'https://i.imgur.com/3KrpgWS.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '11', 'pro', 'max', 'seminovo', 'a13'],
    salesCount: 330, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-12-64gb-seminovo', name: 'iPhone 12 64GB',
    description: 'Chip A14 Bionic, tela Super Retina XDR e design com bordas retas.',
    longDescription: 'O iPhone 12 marca um grande salto em performance e design. Com 5G, chip A14 Bionic e Ceramic Shield, mais resistente que qualquer vidro de smartphone. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1"', Capacidade: '64GB', Chip: 'A14 Bionic', Câmera: 'Dupla de 12MP' },
    price: 1899.00, stock: 30, condition: 'Seminovo', storage: '64GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/Dkfm4kW.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/kCZBBOY.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/16yS0XY.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/8CY1VDW.jpeg')], 
    defaultImage: 'https://i.imgur.com/dIcKTva.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '12', 'seminovo', 'a14'],
    salesCount: 400, isOfficial: false, freeShipping: false,
  },
  {
    id: 'iphone-12-128gb-seminovo', name: 'iPhone 12 128GB',
    description: 'Chip A14 Bionic, tela Super Retina XDR e design com bordas retas.',
    longDescription: 'O iPhone 12 marca um grande salto em performance e design. Com 5G, chip A14 Bionic e Ceramic Shield, mais resistente que qualquer vidro de smartphone. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1"', Capacidade: '128GB', Chip: 'A14 Bionic', Câmera: 'Dupla de 12MP' },
    price: 1999.00, stock: 25, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/Dkfm4kW.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/kCZBBOY.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/16yS0XY.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/8CY1VDW.jpeg')], 
    defaultImage: 'https://i.imgur.com/dIcKTva.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '12', 'seminovo', 'a14'],
    salesCount: 550, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-12-pro-128gb-seminovo', name: 'iPhone 12 Pro 128GB',
    description: 'Sistema de câmera Pro, 5G, A14 Bionic e design em aço inoxidável cirúrgico.',
    longDescription: 'O iPhone 12 Pro vai além. Com scanner LiDAR para experiências de AR aprimoradas e fotografia noturna de nível profissional. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1"', Capacidade: '128GB', Chip: 'A14 Bionic', Câmera: 'Tripla de 12MP com LiDAR' },
    price: 2399.00, stock: 20, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/y1ZkBpE.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/3fVDMKZ.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/vK9V3dS.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/EiAcxFV.jpeg')], 
    defaultImage: 'https://i.imgur.com/1hooQd3.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '12', 'pro', 'seminovo', 'a14'],
    salesCount: 380, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-12-pro-256gb-seminovo', name: 'iPhone 12 Pro 256GB',
    description: 'Sistema de câmera Pro, 5G, A14 Bionic e design em aço inoxidável cirúrgico.',
    longDescription: 'O iPhone 12 Pro vai além. Com scanner LiDAR para experiências de AR aprimoradas e fotografia noturna de nível profissional. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1"', Capacidade: '256GB', Chip: 'A14 Bionic', Câmera: 'Tripla de 12MP com LiDAR' },
    price: 2799.00, stock: 15, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/y1ZkBpE.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/3fVDMKZ.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/vK9V3dS.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/EiAcxFV.jpeg')], 
    defaultImage: 'https://i.imgur.com/1hooQd3.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '12', 'pro', 'seminovo', 'a14'],
    salesCount: 410, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-12-pro-max-128gb-seminovo', name: 'iPhone 12 Pro Max 128GB',
    description: 'A maior tela Super Retina XDR e o sistema de câmera Pro mais avançado da linha 12.',
    longDescription: 'O iPhone 12 Pro Max maximiza sua experiência com uma tela de 6,7 polegadas e um sistema de câmera com estabilização óptica de imagem por deslocamento de sensor. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7"', Capacidade: '128GB', Chip: 'A14 Bionic', Câmera: 'Tripla de 12MP com LiDAR' },
    price: 2799.00, stock: 18, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/AgsDxyT.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/L4yJlcx.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/qnvGLgq.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/QQ3FCUI.jpeg')], 
    defaultImage: 'https://i.imgur.com/MNvoYR3.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '12', 'pro', 'max', 'seminovo', 'a14'],
    salesCount: 450, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-12-pro-max-256gb-seminovo', name: 'iPhone 12 Pro Max 256GB',
    description: 'A maior tela Super Retina XDR e o sistema de câmera Pro mais avançado da linha 12.',
    longDescription: 'O iPhone 12 Pro Max maximiza sua experiência com uma tela de 6,7 polegadas e um sistema de câmera com estabilização óptica de imagem por deslocamento de sensor. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7"', Capacidade: '256GB', Chip: 'A14 Bionic', Câmera: 'Tripla de 12MP com LiDAR' },
    price: 3199.00, stock: 10, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/AgsDxyT.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/L4yJlcx.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/qnvGLgq.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/QQ3FCUI.jpeg')], 
    defaultImage: 'https://i.imgur.com/MNvoYR3.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '12', 'pro', 'max', 'seminovo', 'a14'],
    salesCount: 390, isOfficial: false, freeShipping: true,
  },
   {
    id: 'iphone-13-128gb-seminovo', name: 'iPhone 13 128GB',
    description: 'Sistema de câmera dupla avançado, chip A15 Bionic e um grande salto na duração da bateria.',
    longDescription: 'O iPhone 13 possui uma tela Super Retina XDR brilhante. O chip A15 Bionic ultrarrápido potencializa o Modo Cinema, Estilos Fotográficos e muito mais. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,1"', Capacidade: '128GB', Chip: 'A15 Bionic', Câmera: 'Dupla de 12MP' },
    price: 2399.00, stock: 25, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Verde', '#A7C9A7', 'https://i.imgur.com/xkZXQMv.jpeg'), createColor('Rosa', '#F5D7E3', 'https://i.imgur.com/mTwmeb8.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/ldp8zFE.jpeg'), createColor('Preto', '#2C2C2E', 'https://i.imgur.com/9JhAt8i.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/Qhj7JEX.jpeg')],
    defaultImage: 'https://i.imgur.com/9JhAt8i.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '13', 'seminovo', 'a15'],
    salesCount: 500, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-13-256gb-seminovo', name: 'iPhone 13 256GB',
    description: 'Sistema de câmera dupla avançado, chip A15 Bionic e um grande salto na duração da bateria.',
    longDescription: 'O iPhone 13 possui uma tela Super Retina XDR brilhante. O chip A15 Bionic ultrarrápido potencializa o Modo Cinema, Estilos Fotográficos e muito mais. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,1"', Capacidade: '256GB', Chip: 'A15 Bionic', Câmera: 'Dupla de 12MP' },
    price: 2999.00, stock: 15, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Verde', '#A7C9A7', 'https://i.imgur.com/xkZXQMv.jpeg'), createColor('Rosa', '#F5D7E3', 'https://i.imgur.com/mTwmeb8.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/ldp8zFE.jpeg'), createColor('Preto', '#2C2C2E', 'https://i.imgur.com/9JhAt8i.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/Qhj7JEX.jpeg')],
    defaultImage: 'https://i.imgur.com/9JhAt8i.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '13', 'seminovo', 'a15'],
    salesCount: 320, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-13-pro-128gb-seminovo', name: 'iPhone 13 Pro 128GB',
    description: 'Display ProMotion, o maior upgrade no sistema de câmera Pro e o chip A15 Bionic.',
    longDescription: 'O iPhone 13 Pro é um salto gigante. Tela Super Retina XDR com ProMotion para uma sensação mais rápida e responsiva. Modo Cinema e Fotografia macro. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1" com ProMotion', Capacidade: '128GB', Chip: 'A15 Bionic', Câmera: 'Tripla de 12MP' },
    price: 3399.00, stock: 18, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/POwA379.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/9lZpwLp.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/5c4RAlo.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/hYpXova.jpeg')], 
    defaultImage: 'https://i.imgur.com/qFOo8Bv.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '13', 'pro', 'seminovo', 'a15'],
    salesCount: 480, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-13-pro-256gb-seminovo', name: 'iPhone 13 Pro 256GB',
    description: 'Display ProMotion, o maior upgrade no sistema de câmera Pro e o chip A15 Bionic.',
    longDescription: 'O iPhone 13 Pro é um salto gigante. Tela Super Retina XDR com ProMotion para uma sensação mais rápida e responsiva. Modo Cinema e Fotografia macro. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1" com ProMotion', Capacidade: '256GB', Chip: 'A15 Bionic', Câmera: 'Tripla de 12MP' },
    price: 3799.00, stock: 10, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/POwA379.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/9lZpwLp.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/5c4RAlo.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/hYpXova.jpeg')], 
    defaultImage: 'https://i.imgur.com/qFOo8Bv.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '13', 'pro', 'seminovo', 'a15'],
    salesCount: 350, isOfficial: false, freeShipping: true,
  },
   {
    id: 'iphone-13-pro-max-128gb-seminovo', name: 'iPhone 13 Pro Max 128GB',
    description: 'A melhor bateria em um iPhone, display ProMotion e sistema de câmera Pro.',
    longDescription: 'O iPhone 13 Pro Max tem tudo: a maior tela, a melhor performance e o sistema de câmera mais avançado da linha 13. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7" com ProMotion', Capacidade: '128GB', Chip: 'A15 Bionic', Câmera: 'Tripla de 12MP' },
    price: 3399.00, stock: 20, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/Rtw6bA1.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/mF02oOD.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/OFE2W93.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/QfcEsK1.jpeg')], 
    defaultImage: 'https://i.imgur.com/NCW4N4J.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '13', 'pro', 'max', 'seminovo', 'a15'],
    salesCount: 520, isOfficial: false, freeShipping: true,
  },
   {
    id: 'iphone-13-pro-max-256gb-seminovo', name: 'iPhone 13 Pro Max 256GB',
    description: 'A melhor bateria em um iPhone, display ProMotion e sistema de câmera Pro.',
    longDescription: 'O iPhone 13 Pro Max tem tudo: a maior tela, a melhor performance e o sistema de câmera mais avançado da linha 13. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7" com ProMotion', Capacidade: '256GB', Chip: 'A15 Bionic', Câmera: 'Tripla de 12MP' },
    price: 3799.00, stock: 12, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Prata', '#E5E4E2', 'https://i.imgur.com/Rtw6bA1.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/mF02oOD.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/OFE2W93.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/QfcEsK1.jpeg')], 
    defaultImage: 'https://i.imgur.com/NCW4N4J.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '13', 'pro', 'max', 'seminovo', 'a15'],
    salesCount: 410, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-14-128gb-seminovo', name: 'iPhone 14 128GB',
    description: 'Com detecção de acidente, a maior autonomia de sempre e fotos ainda mais espetaculares com pouca luz.',
    longDescription: 'O iPhone 14 vem com Deteção de acidente, uma funcionalidade de segurança vital que liga para o 112 por si. A maior autonomia de sempre e fotos ainda mais espetaculares com pouca luz. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,1"', Capacidade: '128GB', Chip: 'A15 Bionic', Câmera: 'Dupla de 12MP' },
    price: 2799.00, stock: 22, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Azul', '#A7C9DE', 'https://i.imgur.com/3Aslqv9.jpeg'), createColor('Lilás', '#E2D8EB', 'https://i.imgur.com/vqbXk6u.jpeg'), createColor('Preto', '#2C2C2E', 'https://i.imgur.com/AChvSaT.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/kMk2v2B.jpeg')], 
    defaultImage: 'https://i.imgur.com/eZiYlOa.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '14', 'seminovo', 'a15'],
    salesCount: 300, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-14-pro-128gb-seminovo', name: 'iPhone 14 Pro 128GB',
    description: 'Dynamic Island, câmera de 48MP e Tela Sempre Ativa. Uma nova forma de interagir com seu iPhone.',
    longDescription: 'O iPhone 14 Pro introduz a Dynamic Island, uma inovação da Apple que integra hardware e software. Câmera Grande-angular de 48 MP para detalhes incríveis. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1" ProMotion', Capacidade: '128GB', Chip: 'A16 Bionic', Câmera: 'Tripla 48MP' },
    price: 3699.00, stock: 18, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Roxo', '#C7BEDD', 'https://i.imgur.com/nu9fTX0.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/fLhALtt.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/drgu88M.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/Uc5SFMT.jpeg')], 
    defaultImage: 'https://i.imgur.com/SZ57bwi.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '14', 'pro', 'seminovo', 'a16'],
    salesCount: 450, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-14-pro-256gb-seminovo', name: 'iPhone 14 Pro 256GB',
    description: 'Dynamic Island, câmera de 48MP e Tela Sempre Ativa. Uma nova forma de interagir com seu iPhone.',
    longDescription: 'O iPhone 14 Pro introduz a Dynamic Island, uma inovação da Apple que integra hardware e software. Câmera Grande-angular de 48 MP para detalhes incríveis. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1" ProMotion', Capacidade: '256GB', Chip: 'A16 Bionic', Câmera: 'Tripla 48MP' },
    price: 4099.00, stock: 11, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Roxo', '#C7BEDD', 'https://i.imgur.com/nu9fTX0.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/fLhALtt.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/drgu88M.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/Uc5SFMT.jpeg')], 
    defaultImage: 'https://i.imgur.com/SZ57bwi.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '14', 'pro', 'seminovo', 'a16'],
    salesCount: 320, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-14-pro-max-128gb-seminovo', name: 'iPhone 14 Pro Max 128GB',
    description: 'A experiência Pro em uma tela gigante de 6,7 polegadas. Dynamic Island e a melhor bateria.',
    longDescription: 'O iPhone 14 Pro Max oferece tudo do Pro em uma tela maior. Ideal para produtividade e entretenimento, com uma autonomia que dura o dia todo. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7" ProMotion', Capacidade: '128GB', Chip: 'A16 Bionic', Câmera: 'Tripla 48MP' },
    price: 4199.00, stock: 16, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Roxo', '#C7BEDD', 'https://i.imgur.com/26wOFNo.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/vYUhtgx.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/AxLGhTx.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/KkQstN7.jpeg')], 
    defaultImage: 'https://i.imgur.com/p2TCuUK.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '14', 'pro', 'max', 'seminovo', 'a16'],
    salesCount: 510, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-14-pro-max-256gb-seminovo', name: 'iPhone 14 Pro Max 256GB',
    description: 'A experiência Pro em uma tela gigante de 6,7 polegadas. Dynamic Island e a melhor bateria.',
    longDescription: 'O iPhone 14 Pro Max oferece tudo do Pro em uma tela maior. Ideal para produtividade e entretenimento, com uma autonomia que dura o dia todo. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7" ProMotion', Capacidade: '256GB', Chip: 'A16 Bionic', Câmera: 'Tripla 48MP' },
    price: 4499.00, stock: 9, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Roxo', '#C7BEDD', 'https://i.imgur.com/26wOFNo.jpeg'), createColor('Dourado', '#F5DDC5', 'https://i.imgur.com/vYUhtgx.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/AxLGhTx.jpeg'), createColor('Cinza-espacial', '#5A5957', 'https://i.imgur.com/KkQstN7.jpeg')], 
    defaultImage: 'https://i.imgur.com/p2TCuUK.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '14', 'pro', 'max', 'seminovo', 'a16'],
    salesCount: 430, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-15-128gb-seminovo', name: 'iPhone 15 128GB',
    description: 'Dynamic Island, câmera grande-angular de 48MP e USB-C. Tudo em um design resistente.',
    longDescription: 'A Dynamic Island mostra alertas e Atividades ao Vivo para você não perder nada. Veja quem está ligando, o status do seu voo e muito mais. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,1"', Capacidade: '128GB', Chip: 'A16 Bionic', Câmera: 'Grande-angular 48MP' },
    price: 3699.00, stock: 20, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Azul', '#A7C9DE', 'https://i.imgur.com/LDOA9wJ.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/3ARvxwQ.jpeg'), createColor('Preto', '#2C2C2E', 'https://i.imgur.com/FNkTVpY.jpeg'), createColor('Rosa', '#F5D7E3', 'https://i.imgur.com/PUQ3A1B.jpeg'), createColor('Amarelo', '#FDE48B', 'https://i.imgur.com/d3PUqtM.jpeg')],
    defaultImage: 'https://i.imgur.com/ANo8bjh.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '15', 'seminovo', 'a16'],
    salesCount: 220, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-15-plus-128gb-seminovo', name: 'iPhone 15 Plus 128GB',
    description: 'Tela grande, Dynamic Island e uma bateria incrível. O iPhone 15 em tamanho Plus.',
    longDescription: 'O iPhone 15 Plus traz a Dynamic Island e a câmera de 48MP para uma tela Super Retina XDR de 6,7 polegadas. Bateria com duração impressionante. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR de 6,7"', Capacidade: '128GB', Chip: 'A16 Bionic', Câmera: 'Grande-angular 48MP' },
    price: 3999.00, stock: 15, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Azul', '#A7C9DE', 'https://i.imgur.com/DCzcxE6.jpeg'), createColor('Verde', '#A7C9A7', 'https://i.imgur.com/KROtGCJ.jpeg'), createColor('Preto', '#2C2C2E', 'https://i.imgur.com/a9d3Ojk.jpeg'), createColor('Rosa', '#F5D7E3', 'https://i.imgur.com/ykEAQDx.jpeg')], 
    defaultImage: 'https://i.imgur.com/QkA48A5.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '15', 'plus', 'seminovo', 'a16'],
    salesCount: 180, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-15-pro-128gb-seminovo', name: 'iPhone 15 Pro 128GB',
    description: 'Forjado em titânio, com o chip A17 Pro, botão de Ação configurável e o sistema de câmera Pro mais versátil.',
    longDescription: 'O iPhone 15 Pro é um salto em performance com o chip A17 Pro, que redefine o que é possível em um smartphone. Design em titânio aeroespacial. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,1" ProMotion', Capacidade: '128GB', Chip: 'A17 Pro', Câmera: 'Tripla 48MP' },
    price: 4499.00, stock: 12, condition: 'Seminovo', storage: '128GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/NPWlCy6.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/JH1WtSG.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/wUrP5z5.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/xJqOXdh.jpeg')], 
    defaultImage: 'https://i.imgur.com/QjouWGK.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '15', 'pro', 'seminovo', 'a17pro'],
    salesCount: 310, isOfficial: false, freeShipping: true,
  },
  {
    id: 'iphone-15-pro-max-256gb-seminovo', name: 'iPhone 15 Pro Max 256GB',
    description: 'A experiência Pro definitiva com zoom óptico de 5x, chip A17 Pro e design em titânio.',
    longDescription: 'O iPhone 15 Pro Max tem o maior zoom óptico em um iPhone, perfeito para closes nítidos de longe. Chip A17 Pro para performance de nível profissional. Aparelho seminovo inspecionado e garantido.',
    technicalSpecs: { Tela: 'Super Retina XDR 6,7" ProMotion', Capacidade: '256GB', Chip: 'A17 Pro', Câmera: 'Tripla 48MP com Zoom 5x' },
    price: 5399.00, stock: 10, condition: 'Seminovo', storage: '256GB',
    availableColors: [createColor('Preto', '#2C2C2E', 'https://i.imgur.com/nyZxF40.jpeg'), createColor('Branco', '#F5F5F7', 'https://i.imgur.com/AhWqkry.jpeg'), createColor('Azul', '#A7C9DE', 'https://i.imgur.com/RiNBTmF.jpeg'), createColor('Prata', '#E5E4E2', 'https://i.imgur.com/pVGD50l.jpeg')], 
    defaultImage: 'https://i.imgur.com/9fnvwUt.jpeg',
    warranty: '3 meses', category: 'iPhone', tags: ['iphone', '15', 'pro', 'max', 'seminovo', 'a17pro'],
    salesCount: 290, isOfficial: false, freeShipping: true,
  },
];


export const MOCK_ORDERS: Order[] = [];

export const MOCK_COUPONS: Coupon[] = [
    { id: '1', code: 'PROMO10', discountPercent: 10, expiryDate: '2025-12-31', maxUses: 100, usedCount: 15 },
    { id: '2', code: 'IPHONE20', discountPercent: 20, expiryDate: '2024-10-31', maxUses: 50, usedCount: 45 },
    { id: '3', code: 'EXPIRED', discountPercent: 5, expiryDate: '2022-01-01', maxUses: 10, usedCount: 10 },
];

export const MOCK_MESSAGES: ContactMessage[] = [
    { id: 1, name: 'Joana', email: 'joana@email.com', message: 'Gostaria de saber mais sobre a garantia.', date: new Date(Date.now() - 86400000).toISOString() },
    { id: 2, name: 'Carlos', email: 'carlos@email.com', message: 'Vocês aceitam troca por aparelho usado?', date: new Date(Date.now() - 172800000).toISOString() }
];

export const MOCK_STAFF: Staff[] = [
    { id: '1', email: 'admin@admin.com', password: 'admin', role: 'Admin' },
    { id: '2', email: 'suporte@admin.com', password: 'suporte', role: 'Suporte' }
];